// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.ArrayList;
import java.util.List;


public class TestOPBank {
	private WebDriver driver;
	JavascriptExecutor js;

	@Before
	public void setUp() {

		System.setProperty("webdriver.chrome.driver", "/tmp/selenium/chromedriver/chromedriver");
	}

	@After
	public void tearDown() {

	}

	@Test
	public void ABTestRunner() {
		for (int i = 0; i < 3; i++) {

			driver = new ChromeDriver();
			driver.manage().deleteAllCookies();
			js = (JavascriptExecutor) driver;
			driver.get("https://op.dxpc.ddns.net");
			driver.manage().window().setSize(new Dimension(1536, 835));

			sleeper(6000);

			driver.manage().deleteAllCookies();

			sleeper(2000);

			driver.quit();
		}
	}

	private void sleeper(int millis) {
		try {
			Thread.sleep(millis);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}

