// Generated by Selenium IDE
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;


public class TestRetailUserDxpInsurance {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  
	System.setProperty("webdriver.chrome.driver", "C:/selenium/chromedriver.exe");
        
  }
  @After
  public void tearDown() {
    
  }
  @Test
  public void testretailuserpath() {
	  
  List<String> listUsers = new ArrayList<>();
  listUsers.add("roberto@leoauto.demo"); 
  listUsers.add("david@ccwest.com");
  listUsers.add("robert.daley@email.com");
  listUsers.add("frank.gonzalez@speedyrepair.com");
  listUsers.add("caleb@sauto.demo");
  listUsers.add("hannah.kim@honestauto.com");
  
  for (int i = 0; i < 20; i++) {
	  	
	  	System.out.println("This is run " + i);
	  
	  	for (int f = 0; f < listUsers.size(); f++)
	  		
	  	{
	  	//for each user open a new chrome instance and delete the cookies
	  	driver = new ChromeDriver();
	  	driver.manage().deleteAllCookies();
	  	
	  	js = (JavascriptExecutor) driver;        
	  	System.out.println("Running for " + listUsers.get(f));
	    driver.get("https://demo2.liferayuk.com");
	    driver.manage().window().setSize(new Dimension(1536, 835));
	    driver.findElement(By.id("_com_liferay_login_web_portlet_LoginPortlet_login")).sendKeys(Keys.chord(Keys.CONTROL, "a"));;
	    driver.findElement(By.id("_com_liferay_login_web_portlet_LoginPortlet_login")).sendKeys(Keys.DELETE);
	    driver.findElement(By.id("_com_liferay_login_web_portlet_LoginPortlet_login")).sendKeys(listUsers.get(f));
	    driver.findElement(By.id("_com_liferay_login_web_portlet_LoginPortlet_password")).sendKeys("test"); 
	    driver.findElement(By.id("_com_liferay_login_web_portlet_LoginPortlet_login")).sendKeys(Keys.ENTER);
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    driver.findElement(By.name("q")).click();
	    driver.findElement(By.name("q")).sendKeys(Keys.chord(Keys.CONTROL, "a"));;
	    driver.findElement(By.name("q")).sendKeys(Keys.DELETE);
	    driver.findElement(By.name("q")).sendKeys("turbo");	    
	    driver.findElement(By.name("q")).sendKeys(Keys.RETURN);    
	    
	    
	    try {
			Thread.sleep(5000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 
	    
	    driver.findElement(By.linkText("Turbocharger")).click();
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 
	    
	    JavascriptExecutor js = (JavascriptExecutor) driver;
	    js.executeScript("window.scrollBy(0,1000)");
	    driver.findElement(By.xpath("//dd/a")).click();
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}  
	    
	    driver.findElement(By.xpath("//a[7]/div/img")).click();
	    
	   	    
	    try {
			Thread.sleep(5000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}  
	    	    
	    driver.findElement(By.linkText("I really need more technical information on Turbocharger MIN1999")).click();
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    driver.navigate().back();
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}  
	    
	    
	    driver.findElement(By.linkText("Troubleshooting and Repair")).click();
	    
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    driver.findElement(By.linkText("Turbocharger MIN1999 overheats....lack of technical information on the site")).click();
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    driver.navigate().back();
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    
	    driver.findElement(By.linkText("Turbocharger MIN1999 overheats....lack of technical information on the site")).click();
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    driver.findElement(By.xpath("//a[6]/div/img")).click();
	  
	   	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    driver.findElement(By.linkText("Minium release MIN1999 Turbo...")).click();
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    driver.navigate().back();
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    driver.findElement(By.linkText("It’s time for fall savings!")).click();
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    driver.navigate().back();
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    driver.navigate().to("https://demo2.liferayuk.com/group/minium/sales-library");
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}	    
	    
	    
	    driver.findElement(By.linkText("Turbochargers Price Book")).click();
	   
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}	
	    
	  	    
	    driver.findElement(By.xpath("//div[2]/a/span")).click();
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    driver.findElement(By.linkText("Download")).click();
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    driver.navigate().to("https://demo2.liferayuk.com/c/portal/logout");      
	    driver.quit();	    
  	}
  }
	  	
  }
}

