// Generated by Selenium IDE
import org.junit.Test;


import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.ElementClickInterceptedException;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;


public class TestRetailUserDxpInsurance {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  
	System.setProperty("webdriver.chrome.driver", "C:/selenium/80/chromedriver.exe");
  }
  @After
  public void tearDown() {
  
  }
  @Test
  public void testretailuserpath() {
	  
  List<String> listUsers = new ArrayList<>();
  listUsers.add("bella@liferay.com");
  listUsers.add("toby@liferay.com");
  listUsers.add("stella@liferay.com");  
  
  List<String> annonymousUsers = new ArrayList();
  annonymousUsers.add("ben.stimpy-flute@liferay.com");
  annonymousUsers.add("jill.barney-applefuzz@liferay.com");
  annonymousUsers.add("jenny.snuff-box@liferay.com");
  annonymousUsers.add("trixie.blue-shuttle@liferay.com");
  boolean annonymousJmPath = false;
  boolean jmPath = false;
  boolean vodafonePath = true
		  ;
  
  if (vodafonePath == true) {
	  vodafonePath(listUsers);
  }
  
  if (annonymousJmPath == true) {
	  annonymousJmPath(annonymousUsers);
  }	  

  else if (jmPath == false) {
	  testRetailPath(listUsers);
  }
  else {
	  jmPath(listUsers);
  }
	  
  
	  	
  }
  
private void vodafonePath(List<String> listUsers) {
	for (int i = 0; i < 300; i++) {	
		  
		  
	  	for (int f = 0; f < listUsers.size(); f++)
	  		
	  	{
	  		
	  	driver = new ChromeDriver();
	  	driver.manage().deleteAllCookies();	
		js = (JavascriptExecutor) driver;
	    driver.get("https://tiercontent.liferayuk.com");
	    driver.manage().window().setSize(new Dimension(1536, 835));
	    driver.findElement(By.cssSelector("#sign-in")).click();
	    driver.findElement(By.id("_com_liferay_login_web_portlet_LoginPortlet_login")).sendKeys(Keys.chord(Keys.CONTROL, "a"));;
	    driver.findElement(By.id("_com_liferay_login_web_portlet_LoginPortlet_login")).sendKeys(Keys.DELETE);
	    driver.findElement(By.id("_com_liferay_login_web_portlet_LoginPortlet_login")).sendKeys(listUsers.get(f));
	    driver.findElement(By.id("_com_liferay_login_web_portlet_LoginPortlet_password")).sendKeys("test"); 
	    driver.findElement(By.id("_com_liferay_login_web_portlet_LoginPortlet_login")).sendKeys(Keys.ENTER);
	    
	    try {
			Thread.sleep(6000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    driver.navigate().to("https://tiercontent.liferayuk.com/web/vodafone/iot");
	    
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    try {
	    	driver.findElement(By.id("fragment-zvvh-04-link")).click();
	    }
	    	catch (ElementClickInterceptedException ec) {
	    		js.executeScript("window.scrollBy(0,1200)");
	    		driver.findElement(By.id("fragment-zvvh-04-link")).click();	    		
	    		
	    	}
	    
	  
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    driver.navigate().to("https://tiercontent.liferayuk.com/web/vodafone/iot-knowledge-base/-/knowledge_base/iot/long-term-evolution-for-machines-lte-m-");
	    	   	
		try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		driver.navigate().to("https://tiercontent.liferayuk.com/web/vodafone/iot-knowledge-base/-/knowledge_base/iot/narrowband-internet-of-things-nb-iot-");
		
		    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    driver.navigate().to("https://tiercontent.liferayuk.com/web/vodafone/iot-message-board/-/message_boards/category/338422");
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    driver.navigate().to("https://tiercontent.liferayuk.com/web/vodafone/iot-message-board/-/message_boards/category/338428");
	    	    
	    		    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    
	    driver.navigate().to("https://tiercontent.liferayuk.com/web/vodafone/iot-message-board/-/message_boards/message/343696");
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    String searchTerm = "";
	    if (f == 0)
		    {
	    	searchTerm = "IoT";			    
		    }
	    else if (f == 1)
	    	{
	    	searchTerm = "NarrowBand";
	    	}
	    else
	    	{
	    	searchTerm = "5g";
	    	}
	    
	    driver.findElement(By.name("q")).click();
	    driver.findElement(By.name("q")).sendKeys(searchTerm); 
	    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    driver.manage().deleteAllCookies();	
	    
	    try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    driver.quit();   
	    
	    }
  }	
}	

private void annonymousJmPath(List<String> annonymousUsers) {
	 for (int i = 0; i < 300; i++) {	
		  
		  
		  	for (int f = 0; f < annonymousUsers.size(); f++)
		  		
		  	{
		  		
		  	driver = new ChromeDriver();
			js = (JavascriptExecutor) driver;
		    driver.get("https://tiercontent.liferayuk.com");
		    driver.manage().window().setSize(new Dimension(1536, 835));
		    	    
		    try {
				Thread.sleep(6000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    js.executeScript("window.scrollBy(0,2600)");
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.findElement(By.id("fragment-anrk-link")).click();	    
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.navigate().to("https://tiercontent.liferayuk.com/web/jm/journals");
		    	   	
			try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			driver.findElement(By.linkText("Liquid Extraction Technologies in Small Channels: A Review")).click();
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.findElement(By.xpath("//section/div/a")).click();
		    
		    		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.navigate().to("https://tiercontent.liferayuk.com/web/jm/journals");
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    js.executeScript("window.scrollBy(0,600)");
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.findElement(By.linkText("Exploring Microemulsion - Prepared Lanthanum Catalysts for Natural Gas Valorisation")).click();
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.findElement(By.xpath("//section/div/a")).click();
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.navigate().to("https://tiercontent.liferayuk.com/web/jm/journals");
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    js.executeScript("window.scrollBy(0,1200)");
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    
		    driver.navigate().to("https://tiercontent.liferayuk.com/web/jm/documents");		    
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    String searchTerm = "";
		    if (f == 0)
			    {
		    	searchTerm = "chemical";			    
			    }
		    else if (f == 1)
		    	{
		    	searchTerm = "lanthanum";
		    	}
		    else
		    	{
		    	searchTerm = "extraction";
		    	}
		    
		    driver.findElement(By.name("q")).click();
		    driver.findElement(By.name("q")).sendKeys(searchTerm); 
		    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.navigate().to("https://tiercontent.liferayuk.com/web/jm/elno");
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}		    
		    
		    js.executeScript("window.scrollBy(0,1200)");
		    
		    try {
				Thread.sleep(2000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}	
		    
		    driver.findElement(By.className("ddm-field-text")).click();
		    driver.findElement(By.className("ddm-field-text")).sendKeys(annonymousUsers.get(f));
		    try {
				Thread.sleep(2000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    driver.findElement(By.className("ddm-field-text")).sendKeys(Keys.TAB);
		    try {
				Thread.sleep(2000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    driver.findElement(By.className("lfr-ddm-form-submit")).click();
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		    js.executeScript("window.scrollBy(0,1200)");
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.findElement(By.className("ddm-field-text")).click();
		    driver.findElement(By.className("ddm-field-text")).sendKeys(Keys.chord(Keys.CONTROL, "a"));;
		    driver.findElement(By.className("ddm-field-text")).sendKeys(Keys.DELETE);
		    driver.findElement(By.className("ddm-field-text")).sendKeys(annonymousUsers.get(f));
		    try {
				Thread.sleep(2000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    driver.findElement(By.className("ddm-field-text")).sendKeys(Keys.TAB);
		    try {
				Thread.sleep(2000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    driver.findElement(By.className("lfr-ddm-form-submit")).click();
		    
		    try {
				Thread.sleep(4000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.findElement(By.xpath("//div[3]/button")).click();
		    
		    try {
				Thread.sleep(4000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.navigate().to("https://tiercontent.liferayuk.com/web/jm");
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.navigate().to("https://tiercontent.liferayuk.com/web/jm/journals");
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.findElement(By.xpath("//a[contains(@href, \'/c/portal/logout\')]")).click();
		    
		    try {
				Thread.sleep(2000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.manage().deleteAllCookies();	
		    
		    try {
				Thread.sleep(2000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    driver.quit();   
		    
		    }
	  }	
	
	
}
private void jmPath(List<String> listUsers) {
	  for (int i = 0; i < 300; i++) {	
		  
		  
		  	for (int f = 0; f < listUsers.size(); f++)
		  		
		  	{
		  		
		  	driver = new ChromeDriver();
		  	driver.manage().deleteAllCookies();	
			js = (JavascriptExecutor) driver;
		    driver.get("https://tiercontent.liferayuk.com");
		    driver.manage().window().setSize(new Dimension(1536, 835));
		    driver.findElement(By.cssSelector("#sign-in")).click();
		    driver.findElement(By.id("_com_liferay_login_web_portlet_LoginPortlet_login")).sendKeys(Keys.chord(Keys.CONTROL, "a"));;
		    driver.findElement(By.id("_com_liferay_login_web_portlet_LoginPortlet_login")).sendKeys(Keys.DELETE);
		    driver.findElement(By.id("_com_liferay_login_web_portlet_LoginPortlet_login")).sendKeys(listUsers.get(f));
		    driver.findElement(By.id("_com_liferay_login_web_portlet_LoginPortlet_password")).sendKeys("test"); 
		    driver.findElement(By.id("_com_liferay_login_web_portlet_LoginPortlet_login")).sendKeys(Keys.ENTER);
		    
		    try {
				Thread.sleep(6000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    js.executeScript("window.scrollBy(0,2600)");
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.findElement(By.id("fragment-anrk-link")).click();	    
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.navigate().to("https://tiercontent.liferayuk.com/web/jm/journals");
		    	   	
			try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			driver.findElement(By.linkText("Liquid Extraction Technologies in Small Channels: A Review")).click();
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.findElement(By.xpath("//section/div/a")).click();
		    
		    		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.navigate().to("https://tiercontent.liferayuk.com/web/jm/journals");
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    js.executeScript("window.scrollBy(0,600)");
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.findElement(By.linkText("Exploring Microemulsion - Prepared Lanthanum Catalysts for Natural Gas Valorisation")).click();
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.findElement(By.xpath("//section/div/a")).click();
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    driver.navigate().to("https://tiercontent.liferayuk.com/web/jm/journals");
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    js.executeScript("window.scrollBy(0,1200)");
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    
		    
		    driver.navigate().to("https://tiercontent.liferayuk.com/web/jm/documents");		    
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    String searchTerm = "";
		    if (f == 0)
			    {
		    	searchTerm = "chemical";			    
			    }
		    else if (f == 1)
		    	{
		    	searchTerm = "lanthanum";
		    	}
		    else
		    	{
		    	searchTerm = "extraction";
		    	}
		    
		    driver.findElement(By.name("q")).click();
		    driver.findElement(By.name("q")).sendKeys(searchTerm); 
		    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    driver.manage().deleteAllCookies();	
		    
		    try {
				Thread.sleep(2000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    driver.quit();   
		    
		    }
	  }	
}

public void testRetailPath(List<String> listUsers) {
	  for (int i = 0; i < 300; i++) {	
		  
		  	for (int f = 0; f < listUsers.size(); f++)
		  		
		  	{
		  		
	  		driver = new ChromeDriver();
			driver.manage().deleteAllCookies();			
			js = (JavascriptExecutor) driver;

		    driver.get("https://tiercontent.liferayuk.com");
		    driver.manage().window().setSize(new Dimension(1536, 835));
		    driver.findElement(By.cssSelector("#sign-in")).click();
		    driver.findElement(By.id("_com_liferay_login_web_portlet_LoginPortlet_login")).sendKeys(Keys.chord(Keys.CONTROL, "a"));;
		    driver.findElement(By.id("_com_liferay_login_web_portlet_LoginPortlet_login")).sendKeys(Keys.DELETE);
		    driver.findElement(By.id("_com_liferay_login_web_portlet_LoginPortlet_login")).sendKeys(listUsers.get(f));
		    driver.findElement(By.id("_com_liferay_login_web_portlet_LoginPortlet_password")).sendKeys("test"); 
		    driver.findElement(By.id("_com_liferay_login_web_portlet_LoginPortlet_login")).sendKeys(Keys.ENTER);
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    driver.findElement(By.xpath("//a[contains(@href, \'https://tiercontent.liferayuk.com/web/dxp-insurance-retail\')]")).click();
		    try {
				Thread.sleep(6000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} 
		    
		    JavascriptExecutor js = (JavascriptExecutor) driver;
		    js.executeScript("window.scrollBy(0,1000)");
		    
		    driver.findElement(By.xpath("//div[2]/div/div/a")).click();	
		    	   	
			try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}   
		
		    driver.findElement(By.xpath("//a[contains(@href, \'https://tiercontent.liferayuk.com/group/dxp-insurance-retail/your-account\')]")).click();
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}  
		    
		    driver.findElement(By.xpath("//a[contains(text(),'your documents')]")).click();	    
		    
		    try {
				Thread.sleep(5000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}  
		    
		    driver.findElement(By.xpath("//div[3]/button")).click();
		    
		  
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}  
		    	    
		    driver.findElement(By.xpath("//div[3]/a")).click();
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}  
		    
		    driver.findElement(By.xpath("//a[contains(text(),'Close')]")).click();
		    
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}  
		    
		    driver.findElement(By.xpath("//a[contains(@href, \'/c/portal/logout\')]")).click();
		    
		    try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		    driver.manage().deleteAllCookies();	
		    driver.quit();
	  	}
	  }
    }
}

